
name: Perform synth on stack

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    #- name: Set up Node so we can install CDK
    #  uses: actions/setup-node@v4
    #  with:
    #    node-version: "18"
    
    - name: Install CDK
      using: node18
      run: npm install -g aws-cdk
    
    - name: Verify Synth works to validate stack
      run: cdk synth --validation --context accountId=123456789 east 